In [1]:
%matplotlib inline
import numpy as np
from proj1_helpers import *
from implementations import *
from helpers import *
%load_ext autoreload
%autoreload 2

In [32]:
y, features, ids = load_csv_data('train.csv')
yTest , featuresTest, idsTest = load_csv_data('test.csv')

In [35]:

def create_dataset(dataset, y):
    index = np.where(dataset[:,22] == 0)
    jet_0 = dataset[index]
    y0 = y[index]
    
    index = np.where(dataset[:,22] == 1)
    jet_1 = dataset[index]
    y1 = y[index]
    
    index = np.where((dataset[:,22] == 2) | (dataset[:,22] == 3))
    jet_2_3 = dataset[index]
    y2_3 = y[index]
    

    #Try removing the first features
    jet_0 = np.delete(jet_0, [4, 5, 6, 12, 22, 23, 24, 25, 26, 27, 28], 1)
    jet_1 = np.delete(jet_1, [4, 5, 6, 12, 22, 26, 27, 28], 1)
    jet_2_3 = np.delete(jet_2_3, 22, 1)
    
    return jet_0, jet_1, jet_2_3, y0, y1, y2_3

In [36]:
jet0_train, jet1_train, jet2_3_train, y0_train, y1_train, y2_3_train = create_dataset(features, y)
jet0_test, jet1_test, jet2_3_test, y0_test, y1_test, y2_3_test = create_dataset(featuresTest, yTest)


(array([     3,      4,      8, ..., 249996, 249998, 249999], dtype=int64),)
(array([     1,      2,      7, ..., 249989, 249991, 249997], dtype=int64),)
(array([     0,      5,      6, ..., 249992, 249993, 249994], dtype=int64),)
(array([     0,      2,      3, ..., 568232, 568235, 568237], dtype=int64),)
(array([     1,      6,     10, ..., 568227, 568231, 568236], dtype=int64),)
(array([     4,      7,      9, ..., 568230, 568233, 568234], dtype=int64),)
